# fly.toml app configuration file generated for dashboard-jira on 2026-07-14T11:42:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dashboard-jira'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  CACHE_TTL_SECONDS = '300'
  PLATFORM_DETECTION = 'true'
  PORT = '3000'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
